
CREATE TABLE IF NOT EXISTS wines(
    id INT GENERATED BY DEFAULT as IDENTITY PRIMARY KEY ,
    name TEXT NOT NULL,
    estate TEXT,
    appellation TEXT,
    description TEXT,
    price FLOAT NOT NULL,
    alcohol_percentage FLOAT NOT NULL,
    region TEXT,
    year INT NOT NULL,
    wine_colors TEXT NOT NULL ,
    grape_varieties TEXT[] NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews(
    id INT GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,
    score INT,
    comment TEXT,
    created_at TIMESTAMP NOT NULL,
    wine_id INT,
    FOREIGN KEY (wine_id) references wines(id)
);
